### PR TITLE
Making external links open in new tab

### PR DESCRIPTION
**Pull request by agratapatel**
Added target="_blank" rel="noopener noreferrer" on all the external links so they open in new tab

### CODE REVIEW

**Comment by nburka** [comment]
I'm willing to be overridden on this, but I'm hesitant to open new tabs for external links. There are a bunch of opinions on this, but I think the web is meant to have back buttons, and the points here are valid https://css-tricks.com/use-target_blank/

**Comment by sgarrity** [comment]
I agree with @nburka that we should avoid opening links in new windows/tabs. That said, it is a bit jarring to have two of the main nav links take you off the site. The GitHub link is pretty clear that it'll take you off site, but there's nothing to distinguish the "Request an Icon" and "About" links, though they have significantly different behaviour.

I suggest we make a new page on healthicons.org for "Request an Icon" that explains the process and links to the New Issue template on GitHub.

**Comment by nburka** [comment]
I've made an Issue for what Steven mentioned https://github.com/resolvetosavelives/healthicons/issues/56

**Comment by agratapatel** [comment]
agreed! We can change the expectations from request an icon by changing the content. Perhaps something on the lines of "Request an icon on github" will suit better

**Pull request closed without merging**
