### PR TITLE
Important small changes... see note.

### PR DESCRIPTION
**Pull request by dburka**
Fixed a broken icon. Added BETA to logo. Added @2x PNG downloads for all icons.

### CODE REVIEW

**Comment by sgarrity** [comment]
@dburka The header is too wide for the layout at some in-between viewport sizes. We could just crank up the min-width on the media query that swaps the mobile/desktop header layout a bit: 
image

**Comment by nburka** [comment]
> @dburka The header is too wide for the layout at some in-between viewport sizes. We could just crank up the min-width on the media query that swaps the mobile/desktop header layout a bit:

Let's do that as another PR

**Comment by sgarrity** [comment]
> Let's do that as another PR

I'll do that.

**Comment by sgarrity** [comment]
> Let's do that as another PR

Done in https://github.com/resolvetosavelives/healthicons/pull/46

**Pull request merged**
