### PR TITLE
Huge icon update and other fixes.

### PR DESCRIPTION
**Pull request by dburka**
Removed BETA from the logo
Updated all icons.
Made logo bigger.
Reduced spacing of icons.
Changed footer language about licenses.
Replaced the CC0 image.

### CODE REVIEW

**Comment by sgarrity** [comment]
This PR is so enormous, GitHub is struggling under its weight.

Request for next time: Keep any layout/style changes in separate git commits from the bulk icon updates. That'll make them easier to isolate for review/testing.

I'll try to take a look this evening, but if someone else can in the mean time, don't wait for me.

**Comment by sgarrity** [comment]
I'd update the About page to use this new Public Domain badge image too. The white background is baked in - is there an SVG or transparent version of this that would work on the grey background on the about page?

^ This could be addressed in a future PR - doesn't need to block this icon drop.

**Comment by sgarrity** [comment]
> I'd update the About page to use this new Public Domain badge image too. The white background is baked in - is there an SVG or transparent version of this that would work on the grey background on the about page?
> 
> ^ This could be addressed in a future PR - doesn't need to block this icon drop.

Or just use the black border, like you do in the modal.

**Comment by sgarrity** [comment]
I've reviewed the text/UI changes closely. They all look good with some minor feedback that can be addressed in a later PR. The icon update is too huge to review individually. I'm going to merge and let the internet gods sort it out.

**Comment by sgarrity** [comment]
@dburka I turned my feedback on this PR into a new PR with fixes. They're all minor: https://github.com/resolvetosavelives/healthicons/pull/134

**Comment by nburka** [comment]
I merged 134

**Pull request merged**
